server:
  port: 8080
spring:
  application:
    name: gatewaydemo2
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: add_request_param
#          uri: http://localhost:8081  # http://localhost:8080/foo 产生效果
          uri: lb://spring-cloud-producer # http://localhost:8080/foo 负载均衡
          filters:
            - AddRequestParameter=foo,bar
          predicates:
            - Method=GET

eureka: # http://localhost:8080/SPRING-CLOUD-PRODUCER/hello?name=spring 负载均衡
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug