server:
  port: 8080
spring:
  application:
    name: gateway1
  cloud:
    gateway:
      routes:
        - id: gateway-service
          uri: https://www.baidu.com
          order: 0
          predicates:
#            - Host=**.foo.org
#            - Path=/headers
#            - Method=GET
#            - Header=X-Request-Id, \d+
#            - Query=foo, ba.
#            - Query=baz
#            - Cookie=chocolate, ch.p
            - After=2018-01-20T06:06:06+08:00[Asia/Shanghai]